services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  web:
    build: .
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    ports:
      - '5000:5000'
    depends_on:
      - redis