apiVersion: v1
kind: ServiceAccount
metadata:
  name: pac-builder
  namespace: pac-dogfood
  annotations:
    # This service account uses GKE workload identity to map to a
    # Google service account that has permissions to push to this
    # Google Artifact Registry repo.
    iam.gke.io/gcp-service-account: pac-builder@tekton-interns.iam.gserviceaccount.com
---